#!/bin/bash

if [ "$EUID" -ne 0 ]; then
	printf "Please run scripts as root\n"
	exit;
fi

#Interface to be configured
interface="enp0s3"

#Flush iptables

iptables -F

printf "Flushed iptables\n"

#Policies

iptables -P OUTPUT DROP
iptables -P INPUT DROP
iptables -P FORWARD DROP

printf "Setup default policies\n"

#Input Chain Rules

iptables -A INPUT -i lo -j ACCEPT

#Allow ssh
#iptables -A INPUT -i $interface -p tcp --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT

#Allow established connections
#iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -i $interface -p tcp --sport 80 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -i $interface -p tcp --sport 443 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -i $interface -p tcp --sport 53 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -i $interface -p udp --sport 53 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -i $interface -p icmp --icmp-type echo-reply -j ACCEPT
printf "Setup input rules\n"

#Output Chain Rules

iptables -A OUTPUT -o lo -j ACCEPT

iptables -A OUTPUT -o $interface -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -o $interface -p tcp --dport 53 -j ACCEPT
iptables -A OUTPUT -o $interface -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -o $interface -p udp --dport 67:68 -j ACCEPT
iptables -A OUTPUT -o $interface -p tcp --dport 443 -j ACCEPT
#Allow ssh
#iptables -A OUTPUT -o $interface -p tcp --sport 22 -m state --state ESTABLISHED -j ACCEPT
iptables -A OUTPUT -o $interface -p icmp --icmp-type echo-request -j ACCEPT

printf "Setup output rules\n"

#Save Rules
iptables-save > /etc/iptables.conf
results=$(grep "iptables-restore < /etc/iptables.conf" /etc/rc.local)
if [ ${#results} -eq 0 ]; then
	sed -i '/exit 0/iiptables-restore < /etc/iptables.conf' /etc/rc.local
	printf "Added iptables-restore < /etc/iptables.conf to /etc/rc.local\n"
fi

printf "Saved iptables rules\n"
